language: node_js
node_js:
- '8'
before_install:
- wget https://github.com/github/hub/releases/download/v2.2.9/hub-linux-386-2.2.9.tgz
- wget https://kubernetes-helm.storage.googleapis.com/helm-v2.7.2-linux-amd64.tar.gz
- tar -xvzf hub-linux-386-2.2.9.tgz
- tar -xvf helm-v2.7.2-linux-amd64.tar.gz
- export PATH=${PATH}:$PWD/hub-linux-386-2.2.9/bin/:$PWD/linux-amd64
- export GOPATH="${TRAVIS_BUILD_DIR}/Go"
- export PATH="${TRAVIS_BUILD_DIR}/Go/bin:${PATH}"
- npm i -g markdown-to-html
before_script:
- git clone -b v2 git@github.ibm.com:bluemix-mobile-services/bmd-devops-pipeline.git
- cd /tmp
- git clone -b master https://github.com/ibm-developer/changelog-generator-slack-notification.git
- npm install changelog-generator-slack-notification
- cd -
- sh ./bmd-devops-pipeline/scripts/setnpmrc.sh
script: npm test && bash ./bmd-devops-pipeline/scripts/npm_version_upgrade.sh
branches:
  only:
  - develop
  - master
  
